# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'globus000/samplebatchapi.netcore'
  repoName: 'Azure'

steps:
- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: "**/*.sln"
- task: MSBuild@1
  inputs:
    solution: 'SampleBatch/SampleBatch.sln'
    msbuildVersion: 'latest'
    msbuildArchitecture: 'x86'
    configuration: 'release'
    clean: True


- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'globus000/samplebatchapi.netcore'
    command: 'buildAndPush'
    Dockerfile: 'SampleBatch/SampleBatchApi.NETCore/Dockerfile'
    tags: 




