# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'globus000/samplebatchapi.netcore'
  repoName: 'Azure'

steps:
- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: "**/*.sln"
- task: MSBuild@1
  inputs:
    solution: 'SampleBatch/SampleBatch.sln'
    msbuildVersion: 'latest'
    msbuildArchitecture: 'x86'
    configuration: 'release'
    clean: True

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: SampleBatchRegistry

- task: Docker@2
  displayName: Build and and push image
  inputs:
    repository: $(repoName)
    command: buildAndPush
    Dockerfile: SampleBatch/SampleBatchApi.NETCore/Dockerfile


- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: SampleBatchRegistry


