# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'globus000/samplebatchapi.netcore'
  repoName: 'Azure'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: "**/*.sln"
- task: MSBuild@1
  inputs:
    solution: 'SampleBatch/SampleBatch.sln'
    msbuildVersion: 'latest'
    msbuildArchitecture: 'x86'
    configuration: '$(buildConfiguration)'
    clean: True

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: "**/Tests/Test.MsgBus.Azure.NETCore/Test.MsgBus.Azure.NETCore.csproj"
    arguments: '--configuration $(buildConfiguration)'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial Subscription(04534d3c-b433-4f7f-ac5d-893d2a2b829a)'
    azureContainerRegistry: '{"loginServer":"samplebatchregistry.azurecr.io", "id" : "/subscriptions/04534d3c-b433-4f7f-ac5d-893d2a2b829a/resourceGroups/SampleBatch00/providers/Microsoft.ContainerRegistry/registries/SampleBatchRegistry"}'
    dockerComposeFile: 'SampleBatch/SampleBatchApi.NETCore/docker-compose.yml'
    action: 'Run a Docker Compose command'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'globus000/samplebatchapi.netcore'
    command: 'buildAndPush'
    Dockerfile: 'SampleBatch/SampleBatchApi.NETCore/Dockerfile'
    tags: 




