# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'globus000/samplebatchapi.netcore'
  repoName: 'Azure'

steps:
- task: MSBuild@1
  inputs:
    solution: 'SampleBatch/SampleBatch.sln'
    msbuildVersion: 'latest'
    msbuildArchitecture: 'x86'
    configuration: 'release'
    clean: True

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(repoName)
    command: build
    Dockerfile: SampleBatch/SampleBatchApi.NETCore/Dockerfile
