apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: globus000-samplebatchapi
  name: globus000-samplebatchapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: globus000-samplebatchapi
  template:
    metadata:
      labels:
        app: globus000-samplebatchapi
    spec:
      containers:
      - image: globus000/samplebatchapi.netcore:latest
        name: globus000-samplebatchapi
        ports:
        - containerPort: 8080
        
        
